[package]
name = "rust_zombie_shooter"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.3"
base64 = "0.21"
image = "0.24"
symphonia = { version = "0.5", features = ["all"] }
